---
language: python
python: "3.8"
os: linux
dist: xenial

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  - pip install pipenv
  - pipenv sync --dev

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - invoke test
